spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/rcdb

    host: 127.0.0.1
    port: 3306

    username: root
    password: ss1235789

  data:
    redis:
      host: localhost
      port: 6379


springdoc:
  api-docs:
    path: /swagger-ui.html


rc:
  jwt:
    secret-key: ERWHOIFHWOICHNDLKVHDSLKFVHDSLFKALFHLAKHSFASHFL
    access-token-expires-minute: 1000000
    refresh-token-expires-day: 14